### PR TITLE
Logging Fixes

### LINKED ISSUE #1508: externalizing log4j2.xml appears to be broken
it appears that CAS is no longer honoring an externalized logging config in 4.3.x. I still need to verify this, but wanted to log it now so it didn't get forgotten.

### PR DESCRIPTION
**Pull request by frett**
Closes #1508

### CODE REVIEW

**Comment by frett** [comment]
2 simple changes, first time working with lambda functions though

**Comment by mmoayyed** [comment]
Looks good to me. Question: why keep null values? what does that provide?

**Comment by frett** [comment]
position of the arguments being processed matters. Where I ran into this was this log statement:

```
2016-02-05 13:43:16,994 DEBUG [org.jasig.cas.util.CasLoggerContextInitializer] - <Updated logging config file from [null] to [file:/Users/frett/opt/tomcat/7.0.65/conf/cas.log4j2.xml]>
```

without this fix the log statement was:
```
2016-02-05 13:43:16,994 DEBUG [org.jasig.cas.util.CasLoggerContextInitializer] - <Updated logging config file from [file:/Users/frett/opt/tomcat/7.0.65/conf/cas.log4j2.xml] to []>
```

which changes the meaning of the message

**Comment by mmoayyed** [comment]
Thanks. :+1:

**Comment by mmoayyed** [comment]
One other question: does it make sense to return "[]" instead of null? So the log would read:

```
<Updated logging config file from [] to  file:/Users/frett/opt/tomcat/7.0.65/conf/cas.log4j2.xml >
```

This is a non-issue, but I think that is easier to digest than trying to figure out what "null" is.

**Comment by frett** [comment]
by sticking with `null` it maintains default logger behavior. I feel we should only globally modify log messages when security is the concern (which is the current case with filtering out tickets)

**Comment by frett** [comment]
I do agree in this case it would be more clear without null, I'll update that on the specific log message and not globally

**Comment by mmoayyed** [comment]
Agreed on keeping the default behavior. Your suggestion sounds like a better plan. Thanks.

**Comment by tduehr** [comment]
I had some issues externalizing configs this week myself. Turns out it was tomcat8 preventing access to anything outside of the  webroot. Fixed by updating tomcats context.xml to mount the files as PreResources. This might be useful information in the externalization doc.

**Pull request merged**
