### PR TITLE
Bootify CAS application context

### LINKED ISSUE #1577: Bootify CAS application context
Take advantage of Spring Boot, to configure the Spring cloud server/client config, specifically. Boot offers a hassle-free xml-free configuration style of the webapp context is able to autoconfigure most of the CAS internals via its autoconfiguration annotations. It also allows CAS to turn into an executable war via an embedded servlet container.

### PR DESCRIPTION
**Pull request by mmoayyed**
Closes #1577 , #1639 , #1640  

Notes will be updated shortly. Much like the MFA functionality, this branch is made available here so that others can collaborate, test and extend the present boot functionality. Work is not finalized yet, but it's in a good-enough shape. We'll likely need to schedule 1-2 review sessions with each other to review changes as a whole, since the changes are very large. 

UX work remains to be completed, and is still WIP. Going to let Travis run tests for the time being. 

Overlay: https://github.com/Jasig/cas-overlay-template/tree/5.0

### CODE REVIEW

**Comment by mmoayyed** [comment]
Tests should be all passing now. I'll continue to test this branch with various modules. @mindblender is also working on a few UX related items for the main and management webapp. We hope to have something available by the end of next week.

**Comment by mmoayyed** [comment]
I am working on a few UI-related changes on the mgmt webapp to make sure Boot works fine there. barring other issues, could we tentatively agree to get this merged by say, May 7th?

**Comment by leleuj** [comment]
Yes, I'd prefer to merge it as soon as possible and fix glitches along the way than let you work endlessly after the master...

**Comment by dima767** [comment]
+1 on merging into master asap

**Comment by mmoayyed** [comment]
Heads up. Barring any other issues, going to move up the merge schedule to this Friday, May 29th. Merges with master are starting to get unruly :)

**Comment by dima767** [comment]
+1. You meant April 29 :-)

**Comment by mmoayyed** [comment]
Yes! :) The weariness from all this merge noise is starting to show.

Going to work on test fixtures to get this and Travis ready before then.

**Comment by mmoayyed** [comment]
All systems go. Let the countdown begin.

**Pull request merged**
