### PR TITLE
Enable the Ticket Cleaner by default

### PR DESCRIPTION
**Pull request by mmoayyed**
Closes https://github.com/Jasig/cas/issues/1585

### CODE REVIEW

**Comment by frett** [comment]
+1

**Comment by frett** [comment]
actually, what happens for TicketRegistries that don't support the cleaner (do we still have some that live in this state)?

**Comment by frett** [comment]
doing a quick look at master, with this set to true I believe `CouchbaseTicketRegistry` and `MemCacheTicketRegistry` will throw an `UnsupportedOperationException` in the cleaner thread which will still be scheduled.

We should probably include a simple internal cleaningSupported flag that TicketRegistries set if they support or don't support cleaning and use that in conjunction with the enabling of the cleaner.

**Comment by mmoayyed** [comment]
Good catch. I should review them and see why don't support it. The cleaner does nothing out of the ordinary I suppose. Havent looked, but can't think of a reason that would cause a registry to not support this behavior.

**Comment by frett** [comment]
the exception would be thrown by the call to `getTickets()`. I have experience with memcache, so I get why that's the case there. There is no way to enumerate all the keys stored in memcache. I'm assuming a similar scenario in Couchbase

**Comment by mmoayyed** [comment]
Reviewed. Per @frett 's suggestion, added a flag to indicate whether the cleaner can be supported by a given registry. Default is true, and the two noted registries override the flag to disable the cleaner, since they are unable to return a collection of tickets that would be processed by the cleaner job.

**Comment by frett** [comment]
+1

**Pull request merged**
