### PR TITLE
Small wiki correction - header level

### PR DESCRIPTION
**Pull request by PetrGasparik**

### CODE REVIEW

**Comment by PetrGasparik** [comment]
can you apply this change to 4.1.x so I can see it on wiki?

**Comment by mmoayyed** [comment]
It will be there in about 30 minutes or so.

**Comment by PetrGasparik** [comment]
thank you. should I always make such doc PR on master, or is it better in branch like 4.1.x?

**Comment by mmoayyed** [comment]
Ideally, it would be best if you could do both :) but that depends on your change. I'd recommend master always, but do what makes sense for you and we can then port it to the appropriate place. Thanks for the contribution.

**Pull request merged**
