### PR TITLE
Updated runtime/test dependencies

### PR DESCRIPTION
**Pull request by mmoayyed**

### CODE REVIEW

**Comment by mmoayyed** [comment]
I had to explicitly define lengths for LOB fields here; otherwise SqlExceptions on data truncation would pop up.

**Comment by leleuj** [comment]
The SqlException was caused by the updated database dependencies, wasn't it?

**Comment by mmoayyed** [comment]
Yes, hsqldb 2.3.2.

**Comment by leleuj** [comment]
+1

**Pull request merged**
