### PR TITLE
Support non-assoc mode of openid

### PR DESCRIPTION
**Pull request by mmoayyed**
Complements https://github.com/Jasig/cas/pull/1557

### CODE REVIEW

**Comment by mmoayyed** [comment]
@ardias You may to test the changes here, which are complementary to what you have now.

**Comment by ardias** [comment]
Ok i will. From the looks of it it should, but i'll try it.

**Comment by mmoayyed** [comment]
@ardias Have you had a chance to try this?

**Comment by ardias** [comment]
Yeah, i applied the changes to  my local server and yes it did work.
Now what's missing is the real 'validation' of the request parameters. I believe in openid4java, the ServerManager can do that validation. It has a method 'verify', that check the various paremeters.

**Comment by mmoayyed** [comment]
You mean on the server side, or the client? because in your app, the verify() method is already getting called I believe.

**Comment by ardias** [comment]
Yes, on the server. The client does a verify when it's in association mode. When it's not is association mode, the client has to send a verification request to the server. 
http://openid.net/specs/openid-authentication-2_0.html#verification (section 11.4.2)

**Comment by mmoayyed** [comment]
OK. very good. Is that something you'd be interested to work on? and if so, shall we merge this so that you can resume?

**Comment by ardias** [comment]
I could work on this but i can't commit to a very strict release/ready date. I'm doing this in my company's time because we're evaluating various auth/sso solutions, and i have a lot of other stuff to do. If there's not a big hurry, i could dedicate some of my free-time.

And, yes if you could merge it, i would appreciate it.

**Comment by mmoayyed** [comment]
Understood. Appreciate your time. So tentative release date for 4.3 is sometime late May 2016. So you have plenty of time to knock this out. I'll ping you from time to time to see whether you need any help, and feel free to post an update on the same issue here. Thanks again.

**Comment by ardias** [comment]
Ok, cool. I'll keep you posted

**Pull request merged**
