### PR TITLE
ADSF/WsFed Support

### LINKED ISSUE #1034: Allow CAS to act as an ADFS client
Allows the cas server to delegate authentications to an ADFS server. Code already exists and module is already available as an extension.

### PR DESCRIPTION
**Pull request by mmoayyed**
Closes #1034 

This method of integrating CAS Server and ADFS delegates user authentication from CAS Server to ADFS. This is accomplished by making CAS Server a WS-Federation client. Claims released from ADFS are made available as attributes to CAS Server, and by extension CAS Clients. This method has the advantage (or disadvantage) that federated users have the potential to participate as user of CAS Clients. Most if not all of the functionality is handled by opensaml as part of the saml module. 

There are essentially 3 steps to configuring this module:

- Configure CAS Server.
- Configure ADFS Server.
- Enabling claims manipulation for CAS consumption.

### CODE REVIEW

**Comment by mmoayyed** [comment]
Heads up; Planning to merge and write docs towards mid next week. Please review when you get a chance.

**Comment by rdev5** [comment]
> Delegation is the process of a computer user handing over their authentication credentials to another user. - [Wikipedia](https://en.wikipedia.org/wiki/Delegation_(computer_security))

> This method of integrating CAS Server and ADFS *delegates* user authentication from CAS Server **to ADFS**

By definition, then, when you say "we've added ADFS/WsFed Support," do you mean:

1. CAS now supports ADFS as another authentication method such that logging into ADFS will authorize you in CAS; or
2. CAS can now be used to single sign-on into ADFS such that logging into CAS will authorize you in ADFS and it follows that CAS may now be used to single sign-on users into Office 365 apps.

Thanks!

**Comment by mmoayyed** [comment]
1. CAS now supports ADFS as another authentication method such that logging into ADFS will authorize you in CAS.

and

2. CAS can now be used to single sign-on into ADFS such that logging into CAS will authorize you in ADFS and it follows that CAS may now be used to single sign-on users into Office 365 apps

**Comment by mmoayyed** [comment]
The latter is only possible in v5.

**Comment by rdev5** [comment]
v5 as in CAS 5?

**Comment by rdev5** [comment]
What about this: https://github.com/Unicon/cas-adfs-integration/wiki/adfs-casification

Seems to convey that we would just need to update ADFS' login page to query ClearPass and auto-login on behalf of the user

**Comment by mmoayyed** [comment]
v5 as in CAS 5. 

And that's a question for that project. Not here.

**Pull request merged**
