### PR TITLE
Ensure SAML UI extensions are not null

### PR DESCRIPTION
**Pull request by mmoayyed**

### CODE REVIEW

**Comment by leleuj** [comment]
The build "nightmare" restarts: I see a failing test on Hazelcast :-(

+1 To be fixed on master as well?

**Comment by mmoayyed** [comment]
Yes. Must be ported over. 

I have no idea what is up with Travis. This is very frustrating. Maybe we could switch to Codeship. Don't know.

**Comment by dima767** [comment]
Let's switch the CI server

**Comment by dima767** [comment]
https://drone.io/

**Comment by mmoayyed** [comment]
This looks promising. Switching is not an easy feat. Might have to put this on the backburner for now.

**Comment by mmoayyed** [comment]
Actually, I take that back :) I don't mind having all 3 CI systems build CAS. That way, we can compare and let them sit for a while and see which one causes less headache!

**Comment by mmoayyed** [comment]
Tested drone.io. Far too limiting. Cant build multiple branches. Max build time set to 15 minutes.

**Pull request merged**
