### PR TITLE
Management webapp redesign

### PR DESCRIPTION
**Pull request by mmoayyed**
Closes https://github.com/Jasig/cas/issues/496

There are a few more issues to work out, but I will leave this pull open as we merge changes into the branch so others can review and test. 

This is the last wrinkle in 4.1 release.

### CODE REVIEW

**Comment by mmoayyed** [comment]
This pull is ready to be merged. All issues have been fixed.

**Comment by mmoayyed** [comment]
ping @leleuj would like to expedite the release. Think we can merge this and work through issues by end of week?

**Comment by leleuj** [comment]
I'm not sure I will have time to review everything, I'll try to take a look at least.

I'll make a test before the end of the week and let you know.

**Comment by mmoayyed** [comment]
Thanks. I'd recommend pulling down the branch and testing it purely from a functional perspective. Code reviews may not be entire feasible as most changes are UI based and I have complete trust in our fellow UI devs to have done a good job. 

We'll mark this to merge by Friday unless you or anyone else discovers bugs.

**Comment by mmoayyed** [comment]
Ping. Getting ready to merge by tomorrow evening EDT.

**Comment by mmoayyed** [comment]
PS I will also merge this branch into heroku

**Comment by leleuj** [comment]
Wow! What a great job! You did that on your own?

I just quickly did a few tests, it seems to work for most of the features I tested. A few comments:
- Ant-pattern service definitions have disappeared on purpose, haven't they?
- there is no text for the tooltip of the "Evaluation Order" field, just the key
- when you check / uncheck the "Require All Attributes" box, I think that the "Required Attributes" zone should appear / disappear.
- for the "Authorized to release to credential password" chekbox, where is the key to encrypt the password? In the "Public Key Options"?
- what is the "Authorized to release proxy granting ticket ID" checkbox? Compared to "Proxy Policy Options"?
- the explanation for the "Attribute Filter Pattern" input field should be improved.
- the explanation for the "Required Handlers" textarea is not clear: "Collection of ids"?
- it's not clear why I want to use the "Public Key Options"
- even in "Edit mode", I have the success message: "Service has been added successfully" (I was expected: "edited") and it's a bit strange to stay on the "Edit service" page after a successful update
- the default service "http://localhost:8080/cas-management/login/cas" does not make any sense
- the "Allow Single Sign-On" checkbox should be selected by default
- typing "http://**" in the "Regex" field for the "Proxy Policy Options" checked to "Regex", I have the unclear error: "An error has occurred while attempting to save the service. Please try again later" (logs are explanatory).

If we have a great UI, why would we move it out of the CAS project? I was in favor of dropping the UI if we could not maintain it, but as we have a great UI and as it heavily relies on the cas-server-core module, I think we should keep it in the CAS project.

**Comment by mmoayyed** [comment]
I did a few parts of it on my own :) I had great help with a few UI experts and I am forever thankful to them. 

- Ant-pattern service definitions have disappeared on purpose, haven't they?

They have not. When you define a pattern, it is first checked to see if it's a valid regex. If not, the code switches back to Ant. I am guessing most patterns you defined where valid regex. 

- there is no text for the tooltip of the "Evaluation Order" field, just the key

That's a bug. I'll review.

- when you check / uncheck the "Require All Attributes" box, I think that the "Required Attributes" zone should appear / disappear.

I brought up this point during development. I was told this is not good UI design. Apparently, you still want the user to keep editing stuff even if that stuff isn't going to be applicable.

- for the "Authorized to release to credential password" chekbox, where is the key to encrypt the password? In the "Public Key Options"?

Yes.

- what is the "Authorized to release proxy granting ticket ID" checkbox? Compared to "Proxy Policy Options"?

The option allows you release the PGT directly in the validation response, provided service is allowed to do proxy authentication. 

- the explanation for the "Attribute Filter Pattern" input field should be improved.
Will review.

- the explanation for the "Required Handlers" textarea is not clear: "Collection of ids"?

Technically, it's a collection of authentication handler bean ids. Will clarify. 

- it's not clear why I want to use the "Public Key Options"

Will clarify. It's used to encrypt credential/PGT data.

- even in "Edit mode", I have the success message: "Service has been added successfully" (I was expected: "edited") and it's a bit strange to stay on the "Edit service" page after a successful update

Agreed. I'll see if I can make the change.

- the default service "http://localhost:8080/cas-management/login/cas" does not make any sense
Not sure I follow. What sort of explanation would you want? 

- the "Allow Single Sign-On" checkbox should be selected by default
Will fix.

- typing "http://**" in the "Regex" field for the "Proxy Policy Options" checked to "Regex", I have the unclear error: "An error has occurred while attempting to save the service. Please try again later" (logs are explanatory).

We can work on this.

**Comment by leleuj** [comment]
OK. Forget my comment about the default service.

**Comment by mmoayyed** [comment]
- when you check / uncheck the "Require All Attributes" box, I think that the "Required Attributes" zone should appear / disappear.

Had a look. This is not true. What the checkbox says, CAS should require all attributes/values to grant access to the service. If left unchecked, the first match will succeed. So, you could still have many attributes defined and they will be ORed together. So the pane should still remain visible.

**Comment by mmoayyed** [comment]
All feedback has been accounted for.

**Comment by mmoayyed** [comment]
So @leleuj I am assuming you are satisfied by the pull?

**Comment by leleuj** [comment]
Yes, great job!
+1

**Pull request merged**
