### PR TITLE
No-Issue: fixing very old package reference in ClearPass documentation

### PR DESCRIPTION
**Pull request by jtgasper3**

### CODE REVIEW

**Comment by leleuj** [comment]
+1

**Comment by leleuj** [comment]
I'm in line, but are we still pushing to `gh-pages` ? I guess we need to use https://github.com/Jasig/cas/tree/master/cas-server-documentation module now.

**Comment by mmoayyed** [comment]
This pull targets 4.x which requires mods to gh-pages.

**Comment by mmoayyed** [comment]
Only master and so forth will allow pulls to the documentation module, which will auto build to gh-pages. We didnt have that process around the 4.x time.

**Pull request merged**
