### PR TITLE
Updated Polish translations for version 4.1.x; issue #994

### PR DESCRIPTION
**Pull request by gerbil14**
Please accept Polish translation File for CAS / CAS Management, completed with all missing entries (based on the English version).

### CODE REVIEW

**Comment by leleuj** [comment]
Looks good to me even if I don't speak Polish.

+1

**Comment by gerbil14** [comment]
Will it also work for the 4.0.x versions?

**Comment by leleuj** [comment]
No, this pull request only targets the master and thus the version 4.1.0. A new pull request must be sent to the 4.0.x branch for version 4.0.x. Be careful as the keys may be different between the versions...

**Comment by mmoayyed** [comment]
Thanks for the pull. :+1:

**Comment by mmoayyed** [comment]
Also #678

**Pull request merged**
