### PR TITLE
Proxy views incorrectly referencing success/failure jsps

### PR DESCRIPTION
**Pull request by mmoayyed**

### CODE REVIEW

**Comment by leleuj** [comment]
+1

**Comment by leleuj** [comment]
It looks like ti breaks the build: https://travis-ci.org/Jasig/cas/jobs/57613591.

**Comment by mmoayyed** [comment]
Just a build fluke. All systems are a go. The test depends on external network fixtures and sometimes, they break for some reason. I verified everything again by running all tests locally.

**Comment by leleuj** [comment]
OK. Great! Sorry for the false positive.

**Pull request merged**
