### PR TITLE
Remove the ticket delegator components.

### LINKED ISSUE #1672: Analyze the use of ticket delegators; remove if necessary
With the current `5.0.0-SNAPSHOT` and enabled HazelcastTicketRegistry, it is severely broken with the following:

1. First, the following exception shows up during the "cleaner business":

```java
...
2016-04-04 09:51:56,151 ERROR [org.quartz.core.ErrorLogger] - <An error occured instantiating job to be executed. job= 'DEFAULT.HazelcastTicketRegistrya06ead4b-eb67-473f-b984-9f4b60e2ef1e'
org.quartz.SchedulerException: Job instantiation failed [See nested exception: java.lang.InstantiationException: org.jasig.cas.ticket.registry.HazelcastTicketRegistry]
	at org.springframework.scheduling.quartz.AdaptableJobFactory.newJob(AdaptableJobFactory.java:45)
	at org.quartz.core.JobRunShell.initialize(JobRunShell.java:127)
	at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:375)
Caused by: java.lang.InstantiationException: org.jasig.cas.ticket.registry.HazelcastTicketRegistry
	at java.lang.Class.newInstance(Class.java:427)
	at org.springframework.scheduling.quartz.AdaptableJobFactory.createJobInstance(AdaptableJobFactory.java:58)
	at org.springframework.scheduling.quartz.SpringBeanJobFactory.createJobInstance(SpringBeanJobFactory.java:74)
	at org.jasig.cas.util.CasSpringBeanJobFactory.createJobInstance(CasSpringBeanJobFactory.java:39)
	at org.springframework.scheduling.quartz.AdaptableJobFactory.newJob(AdaptableJobFactory.java:41)
	... 2 more
Caused by: java.lang.NoSuchMethodException: org.jasig.cas.ticket.registry.HazelcastTicketRegistry.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.newInstance(Class.java:412)
	... 6 more
```

2. Then during the service ticket generation it fails with the following:

```java
...
04-Apr-2016 09:52:35.857 SEVERE [http-nio-8143-exec-9] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [cas] in context with path [/cas] threw exception [Request processing failed; nested exception is org.springframework.webflow.execution.ActionExecutionException: Exception thrown executing org.jasig.cas.web.flow.GenerateServiceTicketAction@13801e21 in state 'generateServiceTicket' of flow 'login' -- action execution attributes were 'map[[empty]]'] with root cause
 java.io.NotSerializableException: org.jasig.cas.ticket.registry.HazelcastTicketRegistry
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.write(JavaDefaultSerializers.java:242)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.write(StreamSerializerAdapter.java:41)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:138)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toData(AbstractSerializationService.java:116)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toData(AbstractSerializationService.java:104)
	at com.hazelcast.map.impl.proxy.MapProxySupport.toData(MapProxySupport.java:944)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.set(MapProxyImpl.java:179)
	at org.jasig.cas.ticket.registry.HazelcastTicketRegistry.addTicket(HazelcastTicketRegistry.java:74)
	at org.jasig.cas.AbstractCentralAuthenticationService.updateTicket(AbstractCentralAuthenticationService.java:257)
	at org.jasig.cas.CentralAuthenticationServiceImpl.evaluatePossibilityOfMixedPrincipals(CentralAuthenticationServiceImpl.java:180)
	at org.jasig.cas.CentralAuthenticationServiceImpl.grantServiceTicket(CentralAuthenticationServiceImpl.java:145)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
...
```
Environment details:

`Tomcat 8.0.32`

```bash
******************** Welcome to CAS *******************
CAS Version: 5.0.0-SNAPSHOT
Build Date/Time: 2016-04-03T15:16:12Z
Java Home: /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre
Java Vendor: Oracle Corporation
Java Version: 1.8.0_45
OS Architecture: x86_64
OS Name: Mac OS X
OS Version: 10.11.3
*******************************************************
```

Steps to re-produce:

1. Clone https://github.com/cas-projects/cas-issues/tree/master/cas-issue-1672 and build with `mvn clean package` (make sure that the local .m2 cache is clean so it pulls the latest snapshot version)

2. Deploy the cas.war

3. Login with `?service=https://www.google.com`

### PR DESCRIPTION
**Pull request by dima767**
Closes #1672

### CODE REVIEW

**Comment by mmoayyed** [comment]
Looks great to me. I'll leave it to @frett to verify and proceed.

**Comment by frett** [comment]
just loading up the jpa ticket registry breaks the webapp at the moment for me. doing a bit more investigating.

**Comment by mmoayyed** [comment]
Working on a few test cases that are now breaking when registries attempt to delete TGTs and children.

**Comment by frett** [comment]
I'm going to try and make some time this weekend to verify functionality in JPA after the couple tweaks @mmoayyed made last night

**Comment by dima767** [comment]
And I'm looking at some of the Oauth test failures

**Comment by dima767** [comment]
There you go @mmoayyed - that's the SSL tests failing I discovered a bit ago with untrustworthy cert of https://www.cacert.org

We should just find a good resource with good SSL cert or just disable those tests relying on https://www.cacert.org for now. Otherwise we'll be getting failing builds...

**Comment by mmoayyed** [comment]
So the trick with that test is that, it actually wants a broken URL. The story is: here is a URL we are trying to reach out to where it has no valid cert publicly, but we have a valid cert for it in a local truststore that we use. So the test is trying to verify that CAS can use its local truststore to reach out to the URL and use the cert in that store. 

Of course, relying on an external resource to verify that for us is painful because it can break at random which appears to be the case here.

**Comment by dima767** [comment]
And so how do we deal about it here - to make the build succeed?

**Comment by mmoayyed** [comment]
Pushed some tweaks; going to let Travis do its thing.

**Comment by mmoayyed** [comment]
All tests passing :) 

So to get the SSL test fixed, I pulled down the new cert for the endpoint, imported it into the local keystore of CAS and removed the previous entry. Then modified Travis to enable a java.security file in the installed Oracle JDK to allow the cert o the loaded (because the cert uses algs and such that are not supported by JDK8 by default)

**Comment by dima767** [comment]
Good stuff, but still, this SSL dependency for the tests is very .. what's the word .. fragile :-)

**Comment by dima767** [comment]
Oh, and what do we (I) do to make the tests pass locally (detailed instructions, please)? :-)

**Comment by frett** [comment]
I'm getting Transaction required errors when trying to login using a simple ticket registry:

```
2016-04-23 16:59:14,817 ERROR [org.jasig.cas.ticket.registry.JpaTicketRegistry] - <Error getting ticket [TGT-**********************************************fcxJ6Op2yM-cas01.example.org, javax.persistence.TransactionRequiredException: no transaction is in progress] from registry.>
```

**Comment by frett** [comment]
well, it appears that the JPA error is on master as well.

**Comment by frett** [comment]
fixed a couple JPA issues on master that showed up when testing. I'm done for the night, hopefully I'll get a chance to continue testing tomorrow with the JPA fixes in place to see what still needs to be done.

**Comment by mmoayyed** [comment]
Going to merge in, so we can resume testing on master with all changes in one place.

**Pull request merged**
