### PR TITLE
Upgrade to Gradle 2.9

### LINKED ISSUE #1289: Gradle 2.9
Gradle 2.9 is out
https://docs.gradle.org/current/release-notes

Release notes indicate a 40% performance boost over 2.8. We should test the new version and possibly upgrade.

### PR DESCRIPTION
**Pull request by mmoayyed**
Closes #1289 

No *significant" performance improvements yet, but incremental builds are a bit faster. I'll let Travis run the build and see how long it might take.

### CODE REVIEW

**Comment by leleuj** [comment]
We don't need the `gradlew.bat` and `gradlew` files in each module: it's cumbersome.

From the root project: `gradlew build` builds everything while `gradlew :module:build` only builds the module named *module*.

I suggest we improve the README or add some "Build the CAS server" documentation page on the new wiki to help people get used to Gradle with CAS.

**Comment by mmoayyed** [comment]
You are right. I ran `gradle wrapper` and it generated everything for me. Will remove them. As for the docs, I think a page under here http://jasig.github.io/cas/developer/ makes better sense.

**Comment by mmoayyed** [comment]
Updated.

**Comment by mmoayyed** [comment]
Will update the docs once the PR merges in.

**Comment by leleuj** [comment]
+1

**Comment by mmoayyed** [comment]
Notes will be available here http://jasig.github.io/cas/developer/Build-Process.html

**Pull request merged**
