### PR TITLE
Enhance error handling of CAS Rest API

### PR DESCRIPTION
**Pull request by dima767**

### CODE REVIEW

**Comment by mmoayyed** [comment]
Fix the build failures please, and move the dependency version over to the gradle.properties file. otherwise, great.

**Comment by dima767** [comment]
How come I don't get those check style errors when I build locally?

**Comment by mmoayyed** [comment]
Hmmm. Does this command not produce them for you?

```
./gradlew build -DskipJavadocs=true -DskipAspectJ=true
```

**Comment by mmoayyed** [comment]
This might also help: http://jasig.github.io/cas/developer/Build-Process.html

**Comment by dima767** [comment]
Interesting... I was using `install` task to build and install the snapshot into a local cache to integration test with the local overlay. Interesting fact is that apparently `install` task _DOES_ disregard the checkstyle noise - which made my happy for a moment there ;-)

**Comment by dima767** [comment]
OK, I will also put the `./gradlew build -DskipJavadocs=true -DskipAspectJ=true` into a convenience shell script, something like `dev-build.sh` and include in this upcoming changeset.

**Comment by mmoayyed** [comment]
Sweet. Thanks. If it helps, I have the following alias if you want to try:

```bash
alias bcas="cd cas-server; cd cas-server-webapp; gradle build --parallel jettyRunWar -x test -DskipJavadocs=true -DskipCheckstyle=true -DskipFindbugs=true -DskipAspectJ=true"
```

Super easy to spin up a new instance.

**Comment by dima767** [comment]
All good here. Working through the checkstyle noise... BTW, within IDEA, in the Gradle tab, one could execute the `checkstyleMain` task for any particular module to get an instant feedback and not wait for the entire build to run!

**Pull request merged**
