### PR TITLE
no need to include cas-server-support-saml as a compile and test dependency

### LINKED ISSUE #1481: support-saml-idp transitive dependency on support-saml not working in overlay
Our local deploy is running into an issue with the transitive dependency on `cas-server-support-saml` from `cas-server-support-saml-idp`.

In the generated pom I'm seeing both of these generated dependencies:

```
    <dependency>
      <groupId>org.jasig.cas</groupId>
      <artifactId>cas-server-support-saml</artifactId>
      <version>4.3.0-SNAPSHOT</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <artifactId>cglib</artifactId>
          <groupId>cglib</groupId>
        </exclusion>
        <exclusion>
          <artifactId>cglib-full</artifactId>
          <groupId>cglib</groupId>
        </exclusion>
      </exclusions>
    </dependency>
```
and later
```
    <dependency>
      <groupId>org.jasig.cas</groupId>
      <artifactId>cas-server-support-saml</artifactId>
      <version>4.3.0-SNAPSHOT</version>
      <scope>test</scope>
      <exclusions>
        <exclusion>
          <artifactId>cglib</artifactId>
          <groupId>cglib</groupId>
        </exclusion>
        <exclusion>
          <artifactId>cglib-full</artifactId>
          <groupId>cglib</groupId>
        </exclusion>
      </exclusions>
    </dependency>
```

it appears that it is including the dependency twice with 2 different scopes (`compile` and `test`). I'm guessing removing the `testCompile` from build.gradle should resolve it.

### PR DESCRIPTION
**Pull request by frett**
closes #1481

### CODE REVIEW

**Comment by frett** [comment]
@mmoayyed from what I can tell this `cas-server-support-saml` shouldn't be needed as a `testCompile` dependency since it's already a `compile` dependency. But I'm not as familiar with gradle as maven, so I might be missing some other hidden effect of declaring it as `testCompile`

**Comment by mmoayyed** [comment]
So as long Travis passes, I am fine :)

**Comment by mmoayyed** [comment]
So @frett just so I understand the case better, you ARE now using cas-server-support-saml-idp? Excellent. I am excited. Please let us know how it goes as you integrate with SPs.

**Comment by frett** [comment]
We have an application that uses SAML that we want to integrate into our SSO environment. This is the first full SAML client that we've needed to integrate and longterm wanted to use the direct CAS support if possible. I saw it was on the roadmap a couple months ago for 4.3. Recently the priority of the integration was raised so we decided as an interim step until 4.3 is available to setup a simple overlay using 4.3 with SAML support configured. One of the other developers at Cru is actually doing this work right now (@hlbraddock)

**Comment by frett** [comment]
merging since travis passed

**Comment by mmoayyed** [comment]
Excellent. Keep us posted please. I am very much in favor of all patches and changes we could apply to make this work, My initial tests against testshib and spring SAML worked flawlessly, but every SP is a bit different and unique. So I am hoping we integrations become more available, we get to improve this further.

**Comment by hlbraddock** [comment]
+1

**Pull request merged**
