### PR TITLE
Fixed typo in documentation

### PR DESCRIPTION
**Pull request by siddharthgoel88**
Documentation had an extra dot. Removed it.

### CODE REVIEW

**Comment by mmoayyed** [comment]
Thank you.

**Comment by mmoayyed** [comment]
BTW, I noticed that you issued thisw PR from your master branch on your fork. While this will work, it might be better in the future to issue PRs from a topic branch on your fork, specially if you plan to contribute more. That will make it much easier for you to switch between branch and stay in sync with our master here.

**Comment by siddharthgoel88** [comment]
Ah ok. I am new to this stuff. I will take of note of it. Thanks for letting me know that :-)  I do that in future.

**Comment by mmoayyed** [comment]
No worries. Look forward to more pulls from you :) Since you're new, I'd suggest that you also sign up the mailing lists and discuss items you'd like to work on, so that we have an idea of what to expect.

**Comment by siddharthgoel88** [comment]
Good idea. I will check official website and subscribe to mailing list and try to get involved :)

**Comment by siddharthgoel88** [comment]
I was wondering, even after my fix for typo I could see the error on http://jasig.github.io/cas/4.0.x/installation/Trusted-Authentication.html page. I thought Travis-CI would publish new changes from Master to gh-pages. Am I wrong?

**Comment by mmoayyed** [comment]
See http://jasig.github.io/cas/development/installation/Trusted-Authentication.html

**Comment by mmoayyed** [comment]
The documentation module always pushes to /development. At this point, we manually merge those changes over to Github pages under 4.0.x, because those files are being serves as static html right now unfortunately. 

I added your change to the 4.0.x tree as well.

**Comment by siddharthgoel88** [comment]
Oh ok. Got it. Thanks.

**Pull request merged**
