### PR TITLE
Added warning for when cookies are disabled

### PR DESCRIPTION
**Pull request by mmoayyed**
Handles https://github.com/Jasig/cas/issues/537

### CODE REVIEW

**Comment by battags** [comment]
I'm not a JavaScript expert, but +1 for the idea :-)

**Comment by leleuj** [comment]
I like the idea as well and I'm no Javascript expert. But doesn't a library exist to do that kind of detection? I think jQuery has a cookie plugin...

**Comment by mmoayyed** [comment]
great suggestions! I'll rework the PR.

**Comment by mmoayyed** [comment]
Added the cookie library for jquery. Much less code :)

**Comment by mmoayyed** [comment]
This one good to go?

**Comment by leleuj** [comment]
Yes +1

**Pull request merged**
