### PR TITLE
Fixed typo in documentation

### PR DESCRIPTION
**Pull request by siddharthgoel88**
Documentation had an extra dot. Removed it.

### CODE REVIEW

**Comment by mmoayyed** [comment]
You want to make the change, not to the gh-pages branch but to the cas-documention module in master.

**Comment by mmoayyed** [comment]
Here to be exact https://github.com/Jasig/cas/blob/master/cas-server-documentation/installation/Trusted-Authentication.md

**Comment by siddharthgoel88** [comment]
Oh ok. I will do that and send the pull request again.

**Comment by mmoayyed** [comment]
Thanks!

**Pull request closed without merging**
