### PR TITLE
Webflow automation for pac4j/wsfed

### PR DESCRIPTION
**Pull request by mmoayyed**
This pull adds a framework around adjustments to the cas webflow dynamically. It also attempts to automate the webflow changes for pac4j and wsfed modules. 

The webflow configurers are moved into a separate module for each feature so that adopters may get a chance to use this behavior optionally.

### CODE REVIEW

**Comment by mmoayyed** [comment]
Try reviewing the changes with https://github.com/Jasig/cas/pull/1306/files?w=1

There are about 2-3 more features that could be automated as such, and I will gradually add those later in other PRs. The abstract class that controls the webflow right now is more of a template with a lot of methods that could be used in the future to augment the flow, specially for MFA.

**Comment by mmoayyed** [comment]
This PR is related to https://github.com/Jasig/cas/issues/1255

**Comment by leleuj** [comment]
It looks good to me. The build needs to be fixed

**Comment by mmoayyed** [comment]
Fixed the build

**Pull request merged**
