### PR TITLE
Checkstyle upgrade to 6.3 [was 6.2]

### PR DESCRIPTION
**Pull request by mmoayyed**

### CODE REVIEW

**Comment by mmoayyed** [comment]
Could I assume we are ok with this PR?

**Comment by leleuj** [comment]
Would you mind giving us some details about this change?

**Comment by mmoayyed** [comment]
Here are the full release notes:
http://checkstyle.sourceforge.net/releasenotes.html

In fact, we are already one revision behind :) I should update this to point to 6.3.

The main motivation is build performance, specially as CS is integrated into the compile phase. We want to be able to take advantage of the latest perf improvements, and possibly do away with buggy checks that might slow the build down or report false negatives.

**Comment by leleuj** [comment]
+1

**Pull request merged**
