### PR TITLE
Update X.509 Authentication Guide

### PR DESCRIPTION
**Pull request by jbjonesjr**
When attempting to follow the X.509 Authentication Guide, I found some errors in the documentation and code snippets. This included:

* [x] mal-formed xml syntax
* [x] deprecated spring webflow properties and beans

This PR addresses these concerns. I have validated the included configurations worked on my clean configuration, of which the details are below:

* Fedora 23
* Oracle JRE 1.8.0_66
* Apache Tomcat 8
* Jasig CAS 4.1.3
* CAS X509 Handler 4.1.3

### CODE REVIEW

**Comment by jbjonesjr** [comment]
**Note:** I'm not quite sure why 212 other files came along with my Pull Request targeting `cas-server-documentation/installation/X509-Authentication.md`, but they did.  I'm happy to update this PR if someone has a suggestion on what branch I should be targeting with this PR.

**Comment by leleuj** [comment]
Indeed, there is a problem: "This branch has conflicts that must be resolved". Are you sure you checkouted your branch from the master to submit a PR to the master?

**Comment by jbjonesjr** [comment]
I apparently did not. Is master the correct branch to be committing this to, or 4.1.X?

**Comment by leleuj** [comment]
I'm not sure. @mmoayyed : can we target a PR for documentation on branch 4.1.x?

**Comment by mmoayyed** [comment]
Sure. 4.1 docs and 4.2 docs build automatically into github pages. Point your target branch to 4.1.

**Comment by mmoayyed** [comment]
You may have to close this PR and create a new one.

**Comment by jbjonesjr** [comment]
ok, this was originally branched from the 4.1.x branch. got the compare to work correct and now it's pointing at the right spot in #1435 . Closing this one.

**Pull request closed without merging**
