### PR TITLE
Remove useless exceptions

### PR DESCRIPTION
**Pull request by mmoayyed**
Reported by @robertoschwald

### CODE REVIEW

**Comment by leleuj** [comment]
Build fails because of checkstyle -> "unused import"...

**Comment by leleuj** [comment]
+1 when the build will be fixed

**Comment by robertoschwald** [comment]
+1 when build is fixed. That was a fast one. Thanks!

**Comment by mmoayyed** [comment]
First build passes. The other is likely a fluke.

**Pull request merged**
