### PR TITLE
OAuth expiration policy for access tokens. 

### LINKED ISSUE #1505: Set specific OAuth timeouts

### PR DESCRIPTION
**Pull request by mmoayyed**
Closes #1505 

@leleuj You should review this. 

Note that expiration policy for codes is handled already.

### CODE REVIEW

**Comment by leleuj** [comment]
Any reason you submit this PR now?

**Comment by mmoayyed** [comment]
No particular reason. Saw an open issue and took it up.

**Comment by mmoayyed** [comment]
Of course, I realized that we now have a policy for oauth codes which I had to do as part of moving around exp policies for proxy tickets, so this was just a natural extension of the same feature.

**Comment by leleuj** [comment]
OK +1

The documentation must be updated as well.

**Comment by mmoayyed** [comment]
Yup. Will do. Tnx.

**Comment by mmoayyed** [comment]
Updated docs

**Pull request merged**
