### PR TITLE
Reset regex servicePattern when the serviceId is changed

### PR DESCRIPTION
**Pull request by frett**
I don't think there are currently any code paths that would trigger this corner case, but it's a simple corner case to protect against.

### CODE REVIEW

**Comment by mmoayyed** [comment]
Thanks. What's with the build failures?

**Comment by frett** [comment]
not sure, it looks like an issue with checkstyle on the yubikey module.

**Comment by mmoayyed** [comment]
Seems that irrelevant. Thanks. How did u run into this change?

**Comment by frett** [comment]
my custom RegisteredService had been using regexs from before support was added to core cas. I've been busy removing several of my own customizations that are now in core cas and stumbled across the fact that it wasn't being reset from one of my own regex tests failing after inheriting the matches function from RegexRegisteredService.

**Comment by mmoayyed** [comment]
Perfect. Thanks. I'll merge this back into appropriate branches.

**Comment by mmoayyed** [comment]
Merged with all branches.

**Pull request merged**
