### PR TITLE
Quartz shutdown on 4.2

### PR DESCRIPTION
**Pull request by frett**
Centralize the Quartz scheduler in spring config to better be able to manage the scheduler lifecycle.

### CODE REVIEW

**Comment by mmoayyed** [comment]
Perfect. Thanks.

**Comment by mmoayyed** [comment]
Are there any other schedulers? I vaguely recall something in the SAML module that would parse metadata for MDUI. Is that not relevant here?

**Comment by frett** [comment]
I did a usage search on `CasSpringBeanJobFactory` to find the schedulers I updated, I'll do a few more usage searches to see if I missed anything.

**Comment by frett** [comment]
I also just noticed an inconsistency in the config values for `ticket.registry.cleaner.startdelay` and `ticket.registry.cleaner.repeatinterval` between the `DefaultTicketRegistry` and `JpaTicketRegistry`.

`JpaTicketRegistry` still defaults to the millisecond values even though it treats them as seconds.

**Comment by mmoayyed** [comment]
Let's switch to seconds, if possible. Doubt anyone would want to configure things as the millli level. 

Also, don't forget to document the new properties in cas.properties for the scheduler.

**Comment by frett** [comment]
actually, `JpaTicketRegistry` still treats them as milliseconds, the inconsistency might confuse deployers

**Comment by frett** [comment]
hmm, the value has historically been milliseconds, based on that the `DefaultTicketRegistry` is where we are handling this incorrectly currently. If we do want to switch to seconds everywhere for consistency, we should document it somewhere for upgrading to 4.2

**Comment by mmoayyed** [comment]
Sure, let's document it too. You could do that in this pull or a separate one, but my vote nonetheless would be to use seconds everywhere. It makes no sense to run jobs every Xms, since most deployers would likely do the math to transform that into seconds or even minutes.

**Comment by frett** [comment]
Alright, I think I got all the quartz schedulers.

**Comment by mmoayyed** [comment]
Awesome. I'd let the build do its thing and then we should be good. 

Just confirming then, with this patch and the earlier log4j change in catalina.properties, are you now able to gracefully shut down tomcat?

**Comment by frett** [comment]
I remember seeing some additional threads left from a stock deploy not related to quartz, checking the log4j config and retesting

**Comment by frett** [comment]
in 4.2 I'm still seeing the log4j2 threads, even though my tomcat config doesn't list those jars on it's exclude list. I'll debug some more for log4j2 and post those findings back on the main issue thread.

**Comment by mmoayyed** [comment]
Looks like this is ready to go. Shall we merge, and investigate further? I'd like to run some tests with this patch in place to see if I still see threads hanging. Sound good?

**Comment by frett** [comment]
sounds good to me

**Comment by mmoayyed** [comment]
I'll cherry pick the changes into master. Will continue to run tests. Thanks Daniel. If you are still testing changes, please keep us in the loop. I'll do a few tests tomorrow as well.

**Pull request merged**
