### PR TITLE
Decode CRL url first before adding to the list

### PR DESCRIPTION
**Pull request by mmoayyed**
Handles https://github.com/Jasig/cas/issues/524

I tested this with and without encoded urls and both check out correctly.

### CODE REVIEW

**Comment by mmoayyed** [comment]
@serac please review.

**Comment by serac** [comment]
I'd like to see a test case, which would help me understand the problem that's being solved. I recall we had a case where the distribution point URL was encoded and it worked, but maybe I'm remembering incorrectly.

**Comment by mmoayyed** [comment]
Sure thing. Coming up...

**Comment by mmoayyed** [comment]
Creating a test cert with encoded distribution points is proving more problematic than I thought. I may have to use mocks in this case. Would that work?

**Comment by mmoayyed** [comment]
I added a test case with a sample cert whose CRL is encoded.

**Comment by mmoayyed** [comment]
To elaborate, the original crl is `http://localhost%3A8085%2Ftest%20ca.crl` which is decoded to `http://localhost:8085/test%20ca.crl`

**Comment by mmoayyed** [comment]
@serac Could I assume this pull passes review?

**Comment by mmoayyed** [comment]
@leleuj you may want to review this

**Comment by leleuj** [comment]
+1

**Pull request merged**
