### PR TITLE
Fix character encoding issue of template rendering

### PR DESCRIPTION
**Pull request by yisiqi**
@mmoayyed  Fix encoding issue which mentioned in #1731.

f9779a60-11d6-11e6-8b76-0ca45819b660

### CODE REVIEW

**Comment by mmoayyed** [comment]
Before pressing merge, could I ask you to:

- Reverse the change
- Find your `application.properties` file and set `spring.thymeleaf.encoding=UTF-8`.
- See what happens

**Comment by yisiqi** [comment]
@mmoayyed

**Comment by yisiqi** [comment]
I just tried exactly same as what you said. 
But still NOT work. 

Please reopen this issue. That closed is a mistaken

**Comment by mmoayyed** [comment]
OK, thanks. What you want to do then is:

1. Add a field to the class of type `ThymeleafProperties` and autowire it.
2. Use that field to do: `setCharacterEncoding(thymeleafProperties.getCharacterEncoding())`

That should work, rather than hardcoding the encoding.

**Pull request merged**
