### PR TITLE
wait for Quartz to shutdown

### PR DESCRIPTION
**Pull request by frett**
also try to interrupt any interruptable jobs

### CODE REVIEW

**Comment by frett** [comment]
addresses Quartz on 4.1 for #1458

**Comment by leleuj** [comment]
Shouldn't these properties be added (yet commented) in the `cas.properties` file?

**Comment by mmoayyed** [comment]
This looks great. One last comment following @leleuj that I think it would be good to explicitly call these properties out in cas.properties, but have them be commented out.

**Comment by mmoayyed** [comment]
@frett Would you be able to apply the last few changes to this patch today? This is holding up the 4.1.x release.

**Comment by frett** [comment]
done

**Comment by mmoayyed** [comment]
Perfect. Thanks.

**Pull request merged**
