### PR TITLE
Dead stores should be removed

### PR DESCRIPTION
**Pull request by kirill-vlasov**
This pull request is focused on resolving occurrences of Sonar rule squid:S1854 - Dead stores should be removed
You can find more information about the issue here:
https://dev.eclipse.org/sonar/coding_rules#q=squid:S1854
Please let me know if you have any questions.
Kirill Vlasov

### CODE REVIEW

**Comment by mmoayyed** [comment]
This is great thank you. how did you find these violations ? please also fix to build failures.

**Comment by mmoayyed** [comment]
Thank you. please fix the bill failures. I think you have a number of unused imports as a result of your changes

**Comment by kirill-vlasov** [comment]
I found the violations by using SonarQube analyzing tool.

**Comment by mmoayyed** [comment]
@kirill-vlasov that something we could easily integrate into the build to run checks automatically?

**Pull request merged**
