### PR TITLE
Fix interval in throttling configuration

### LINKED ISSUE #1608: Interval of scheduled job (to decrement counts) in AbstractInMemoryThrottledSubmissionHandlerInterceptorAdapter doesn't seem correct
In `org.jasig.cas.web.support.AbstractInMemoryThrottledSubmissionHandlerInterceptorAdapter` the refreshinterval defaults to 5000 and is presumably in milliseconds. However the job is scheduled in minutes.

    /**
     * Schedule throttle job.
     */
    @PostConstruct
    public void scheduleThrottleJob() {
        try {
            if (shouldScheduleCleanerJob()) {
                logger.info("Preparing to schedule throttle job");

                final JobDetail job = JobBuilder.newJob(this.getClass())
                    .withIdentity(this.getClass().getSimpleName().concat(UUID.randomUUID().toString()))
                    .build();

                final Trigger trigger = TriggerBuilder.newTrigger()
                    .withIdentity(this.getClass().getSimpleName().concat(UUID.randomUUID().toString()))
                    .startAt(new Date(System.currentTimeMillis() + this.startDelay))
                    .withSchedule(SimpleScheduleBuilder.simpleSchedule()
                        .withIntervalInMinutes(this.refreshInterval)
                        .repeatForever()).build();

                logger.debug("Scheduling {} job", this.getClass().getName());
                scheduler.scheduleJob(job, trigger);
                logger.info("{} will clean tickets every {} seconds",
                    this.getClass().getSimpleName(),
                    TimeUnit.MILLISECONDS.toSeconds(this.refreshInterval));
            }
        } catch (final Exception e){
            logger.warn(e.getMessage(), e);
        }
    }

I think that's a bug.

### PR DESCRIPTION
**Pull request by aukevanleeuwen**
Closes #1608

### CODE REVIEW

**Comment by mmoayyed** [comment]
Good catch! :+1:

**Comment by mmoayyed** [comment]
This will need to be ported forward.

**Comment by aukevanleeuwen** [comment]
@mmoayyed by whom?

**Comment by mmoayyed** [comment]
By me , likely :) Just an announcement so others get the notification.

**Comment by aukevanleeuwen** [comment]
Okay, just checking :-)

**Pull request merged**
