### PR TITLE
Only allow configured parameters in POST requests

### PR DESCRIPTION
**Pull request by leleuj**

### CODE REVIEW

**Comment by mmoayyed** [comment]
:+1: I would however hold off on merging this until 2.0.2 is released.

**Comment by leleuj** [comment]
This depends on: https://github.com/Jasig/cas-server-security-filter/pull/15

As soon as it is merged, I can make a release and update this one to forget about the SNAPSHOT...

**Comment by mmoayyed** [comment]
Sounds good. Thanks.

**Comment by leleuj** [comment]
I will merge it to ensure people test the fix. Then, I'll push a new PR when I'll cut the new `cas-server-security-filter` release (v2.0.2).

**Pull request merged**
