### PR TITLE
Fix aspectj weaving dependencies

### PR DESCRIPTION
**Pull request by mmoayyed**
Closes https://github.com/Jasig/cas/issues/1491

### CODE REVIEW

**Comment by frett** [comment]
looks good to me, I'm guessing it should be back ported to 4.2?

**Comment by mmoayyed** [comment]
Yup. I'll merge back. Were you able to confirm the patch on your end?

**Comment by mmoayyed** [comment]
So I see 4.2 already has this change built-in, I'll tinker with it a bit more to see where the issue is. Let's keep the original issue open.

**Comment by frett** [comment]
alright, just tested on jetty and it's working there, spinning up tomcat now

**Comment by frett** [comment]
and it works on tomcat as well

**Comment by mmoayyed** [comment]
Excellent. Now we just have to figure out what is the difference between 4.2 and master.

**Pull request merged**
