### PR TITLE
Handle vfs resource when checking for CAS date/time

### LINKED ISSUE #1651: CasVersion#getDateTime doesn't work with Wildfly vfs: resource path
1. CAS server version 4.2.0
2. Container type/version Wildfly 9

During server start:
org.jasig.cas.CasVersion#getDateTime falls with IllegalArgumentException on vfs:/... resource path

### PR DESCRIPTION
**Pull request by devpreview**
Closes #1651

For CAS 4.2.x

### CODE REVIEW

**Comment by frett** [comment]
Any reason why you didn't include the logic for the `vfs` protocol? https://github.com/Jasig/cas/pull/1657/files#diff-7b7e27f9135c8a6a25869281a004569fR57

**Comment by devpreview** [comment]
Sorry
See https://github.com/Jasig/cas/compare/4.2.x...devpreview:a8c9a7c

**Comment by frett** [comment]
looks good, waiting for travis to finish before merging

**Comment by devpreview** [comment]
Wildfly 10 deploy error:

> Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: object is not an instance of declaring class
>         at org.jasig.cas.CasVersion.getDateTime_aroundBody2(CasVersion.java:63)

**Comment by frett** [comment]
try a clean build, that looks like an AspectJ error

**Comment by frett** [comment]
hmm, this isn't actually correct usage of `new VfsResource()`.

**Comment by frett** [comment]
@devpreview can you try out this patch: https://github.com/frett/cas/commit/de5e618dcd00d2fb089d20b7a5cb710a560cf553

**Comment by devpreview** [comment]
@frett  Yes now I try
build will take some time

**Comment by devpreview** [comment]
@frett Thanks!
Build successful and delpoyed.

**Pull request merged**
