### PR TITLE
Disable external entities, includes, and entity reference expansion for SAML parsers

### PR DESCRIPTION
**Pull request by mmoayyed**
See https://www.owasp.org/index.php/XML_External_Entity_(XXE)_Processing

### CODE REVIEW

**Comment by mmoayyed** [comment]
Should be merged with 4.2 and 4.1

**Comment by leleuj** [comment]
+1 Looks like we need the same for pac4j ;-)

**Comment by mmoayyed** [comment]
Sure. I'll work on the same pull for pac4j.

**Comment by leleuj** [comment]
Thanks

**Pull request merged**
