### PR TITLE
Add support for Java 8

### PR DESCRIPTION
**Pull request by mmoayyed**
Closes https://github.com/Jasig/cas/issues/957

### CODE REVIEW

**Comment by dima767** [comment]
Good stuff. Now we want to make sure that all tests pass :-)

**Comment by mmoayyed** [comment]
We'd want to ignore codeship for now; since a number of oauth tests require the java 8 JCE to be installed and we can't accommodate that easily via codeship. I spoke to @leleuj about this, and it seems like we'd able to solve that issue with a few updates to the underpinning oauth libs. So I'd leave that one be for now, failing. Travis is where we'd want to focus on, since it's able to install the JCE and get tests passed. I'll see what the failures are all about next.

**Comment by leleuj** [comment]
As JWT support has been removed per #1425, OAuth tests should pass now. In the build, I see a problem with Checkstyle.

**Comment by mmoayyed** [comment]
Working through a few remaining javadoc issues. about 60% done.

**Comment by mmoayyed** [comment]
OK Travis is now fully building the branch. Shall we merge and continue?

**Comment by leleuj** [comment]
I think so, I don't think we have any better option. The change is huge, mostly around date time stuffs. It's better to move on, we'll fix problems in future pull requests (we're on the master and far away from the release date).

**Comment by mmoayyed** [comment]
Sounds good to me. @dima767 @frett  ?

**Comment by dima767** [comment]
+1

**Comment by mkornipati** [comment]
Do we know when we can expect [4.3.0](https://github.com/Jasig/cas/milestones/4.3.0) be released?

**Comment by mmoayyed** [comment]
Keep watching the milestone dates.

**Pull request merged**
